development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis-11939.c11.us-east-1-2.ec2.cloud.redislabs.com:11939" } %>
  channel_prefix: twiksnews_production
