personalized_newseller_job:
  cron: "*/1 * * * *"
  class: "NewsMailerJob"
  queue: default

upd_sources_job:
  cron: "*/1 * * * *"
  class: "UpdateSourcesJob"
  queue: default

upd_articles_job:
  cron: "*/1 * * * *"
  class: "UpdateNewsJob"
  queue: default